### PR TITLE
43-Add-Option-to-Skip-Tutorial

### PR DESCRIPTION
**Pull request by MichalT106**
I added a button where, after clicking on it, the playback of the audio from the tutorial will stop and it will redirect the user to the end of the tutorial.

I also added stopping the audio to the continue button in the tutorials, so that when a person jumps to the next part of the tutorial before the end of the audio, so that multiple audios are not played at once.

You can see the results of the changes here: [Video Title](https://youtu.be/Ks07iIrjv_g)

### CODE REVIEW

**Comment by NateSeymour** [comment]
Hello Michal! 

First off, I think you did an amazing job solving the audio playing/stopping issue. I was aware of the problem but hadn't yet found a solution.

Just to keep the coding style consistent, I would ask that you change a couple of things before I approve your PR:
1. The skip button should match the styling in the Figma. [Here are the reference designs](https://www.figma.com/design/FS3Qcbu6fVLM2gQwAjXWWa/Inspiranza-lo-fi?node-id=0-1&node-type=canvas&t=AcFUZAjkKD19HKZv-0). Maybe you could update the existing Button component in `components/Button.jsx` to have a `style` attribute that could be `primary` or `secondary` depending on whether we want the orange or outlined button.
2. I'm unable to see what your changes do in `(view)/_layout.js`, because unfortunately the standard HTML elements such as `div`, `button`, etc. are not available in React Native. In my development environment is shows an error.
3. We prefer to use `tailwind` for styling components to keep styles visible and logically attached to their objects.

Thank you for your contributions!

**Comment by MichalT106** [comment]
Hi @NateSeymour, so you want the skip button look like this? with the same text? 

image

**Comment by NateSeymour** [comment]
Hi @MichalT106 that's perfect! Here is a screenshot of what it should look like in full context: 

image

**Comment by MichalT106** [comment]
@NateSeymour, And I also need to change the location of the button to the right top corner for merging my implementation or the current position seen in video is okey? Because I am strugling in changing location of button, so the location in video is okey?

**Comment by NateSeymour** [comment]
@MichalT106 Yeah it's a really annoying problem because (as I just learned) `react-native` doesn't support CSS grid. Here is a workaround that you can try:

```JSX
<View className="flex flex-row w-full items-center justify-between px-5">
    <Text className="w-1/3" />
    <Text className="w-1/3 text-center font-alegra-medium text-white text-5xl">
        {tutorial.title}
    </Text>
    <Button className="w-1/3" text="Omitir" />
</View>
```

Here, we first wrap the title in a new `View`, and add a shadow text element to the left and a `Button` to the right. We then create a flexbox with `justify-between` which will push the elements apart. Then we can set the width of all three elements to be 1/3 of the parent `View` so that, in the end, we have a centered title with the button on the right hand side :D

Let me know if that works out for you!

**Comment by MichalT106** [comment]
Hi, @NateSeymour, so the changes are:

- updated the button relevant to figma
- remove of standard HTML elements 
- used tailwind for styling

unfortunately, after a long time, I did not manage to place the button correctly in the upper right corner without disturbing the other objects.

 Well, based on the new changes where I changed button component to add a secondary button, I then used this component in [name].jsx.  In this new implementation of mine, only two files are modified without interfering with global.css or _layout.js for the tutorial view.

Despite the incorrect placement of the button after a long effort, I would like to ask for a review and approval of my implementation, with the bonus of solving the audio stoping problem. 


You can see the results of the changes here: [Video Title](https://www.youtube.com/watch?v=Q9NWdm36dOw)

**Review by NateSeymour — APPROVED** [review]

**Comment by NateSeymour** [comment]
@MichalT106 Thanks for the changes! I'll open a seperate issue for the button positioning. Good work!

**Pull request merged**
